[build]
 command = "npm install && npm run build:client && npm run build --prefix server"  
  publish = "client/dist"
functions = "server/dist/functions"
[functions]
node_bundler = "esbuild"

[dev]
framework = "#vite"
port = 5174

[[redirects]]
from = "/api/*"
to = "/.netlify/functions/api/:splat"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200