[build]
  command = "npm install && npm run build:client && npm run build:server"
  publish = "client/dist"
  functions = "server/dist/functions"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_ENABLED = "false"

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "#vite"
  port = 5174
  targetPort = 5174

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200